---

- name: Install Requirements
  sudo: yes
  pip: name=gunicorn state=present

- name: Create gunicorn Upstart Job
  sudo: yes
  template: src=imager.conf.j2 dest=/etc/init/imager.conf
#   register: config_changes


# - name: Start gunicorn
#   sudo:
#   when: not config_changes.changed
#   service: name=djangoblog state=restarted

  # when: config_changes.changed


- name: Restart gunicorn Upstart Job
  sudo: yes
  service: name=imager state=restarted
