---

- name: Install System Packages
  apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
  sudo: yes
  with_items:
    - build-essential
    - python-dev
    - python-pip
    - postgresql-client
    - libpq-dev
    - python-pip
    - python-psycopg2
    - git
    - libjpeg-dev

- name: Clone Django Repository
  git: repo=https://github.com/jacquestardie/django-imager.git dest={{ django_home }} force=yes

- name: Install Python Dependencies
  sudo: yes
  pip:
    state: present
    requirements: "{{ django_home }}/requirements.txt"

- name: Get DB Hostvars
  set_fact:
    db_host: "{{ hostvars[groups[rds_db_instance][0]] }}"

- name: Get RDS_PASSWORD and SECRET_KEY
  include_vars: secrets.yml

- name: Set DB URL
  set_fact: 
    db_url: "{{ db_host.ec2_engine }}://{{ db_host.ec2_master_username }}:{{ RDS_PASSWORD }}@{{ db_host.ec2__address }}:{{ db_host.ec2__port }}/{{ db_host.ec2_DBName }}"

- name: Make /www directory
  sudo: yes
  file: path=/www state=directory owner=ubuntu group=www-data

- name: Add ubuntu user to www-data
  sudo: yes
  user: name=ubuntu group=www-data

- name: Run Migrations
  environment:
    DATABASE_URL: "{{ db_host.ec2_engine }}://{{ db_host.ec2_master_username }}:{{ RDS_PASSWORD }}@{{ db_host.ec2__address }}:{{ db_host.ec2__port }}/{{ db_host.ec2_DBName }}"
    SECRET_KEY: "{{ SECRET_KEY }}"
    RDS_DB_NAME: "{{ db_host.ec2_DBName }}"
    RDS_USERNAME: "{{ db_host.ec2_master_username }}"
    RDS_PASSWORD: "{{ RDS_PASSWORD }}"
    RDS_HOSTNAME: "{{ db_host.ec2__address }}"
    RDS_PORT: "{{ db_host.ec2__port }}"
    DJANGO_CONFIGURATION: Prod
    DJANGO_SETTINGS_MODULE: imager.settings
  django_manage:
    app_path: "{{ manage_home }}"
    settings: imager.settings
    command: migrate

- name: Collect Static Files
  environment:
    DATABASE_URL: "{{ db_url }}"
    SECRET_KEY: "{{ SECRET_KEY }}"
  django_manage:
    app_path: "{{ manage_home }}"
    settings: imager.settings
    command: collectstatic
